version: '3.9'

services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - .:/var/www:delegated
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./var/nginx:/var/log/nginx
        links:
            - php

    php:
        build:
            context: ./tools/docker/php
        volumes:
            - .:/var/www:delegated

    db:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            TZ: Europe/Paris
            PGTZ: Europe/Paris
        restart: unless-stopped
        volumes:
            - ./.data/postgres:/var/lib/postgresql/data
            - ./var:/var/www/var

    # Dev tools
    adminer:
        image: adminer
        environment:
            APP_ENV: dev
            ADMINER_DESIGN: pepa-linha
            ADMINER_DEFAULT_SERVER: db
        ports:
            - 8888:8080
